# Generated by Django 4.2.7 on 2025-12-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(help_text='Razão Social do associado', max_length=255)),
                ('nome_fantasia', models.CharField(help_text='Nome do associado', max_length=255)),
                ('cnpj', models.CharField(help_text='CNPJ máximo 14 caracteres', max_length=14, unique=True)),
                ('email', models.EmailField(help_text='Email do associado', max_length=254, unique=True)),
                ('telefone', models.CharField(help_text='Telefone do associado', max_length=20)),
                ('endereco', models.TextField(help_text='Endereço completo do associado')),
                ('contrato', models.FileField(blank=True, help_text='Arquivo do contrato', null=True, upload_to='contratos/')),
                ('ficha_cadastral', models.FileField(blank=True, help_text='Arquivo da ficha cadastral', null=True, upload_to='fichas/')),
                ('data_vencimento', models.DateField(help_text='Data de vencimento do associado')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('INATIVO', 'Inativo')], default='ATIVO', help_text='Status do associado', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro do associado')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data de atualização do associado')),
            ],
        ),
    ]
