# Generated by Django 4.2.7 on 2025-12-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.CharField(choices=[('SUSPENSO', 'Suspenso'), ('INATIVO', 'Inativo'), ('ATIVO', 'Ativo')], default='ATIVO', help_text='Status do associado', max_length=10),
        ),
    ]
