# Generated by Django 4.2.7 on 2025-12-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_alter_associado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=10),
        ),
    ]
