# Generated by Django 6.0.1 on 2026-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_alter_associado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='data_ultimo_aviso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
