# Generated by Django 4.2.7 on 2026-01-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('data_vencimento', models.DateField()),
                ('codigo_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('link_pagamento', models.URLField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('plano_conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='financeiro.planodecontas')),
            ],
        ),
    ]
